-- CreateTable
CREATE TABLE "s2023Average" (
    "id" INTEGER NOT NULL,
    "player_name" TEXT NOT NULL,
    "age" INTEGER NOT NULL,
    "games" INTEGER NOT NULL,
    "games_started" INTEGER,
    "minutes" INTEGER,
    "field_goals" INTEGER,
    "field_attempts" INTEGER,
    "field_percent" TEXT,
    "three_fg" INTEGER,
    "three_attempts" INTEGER,
    "three_percent" TEXT,
    "two_fg" INTEGER,
    "two_attempts" INTEGER,
    "two_percent" TEXT,
    "ft" INTEGER,
    "fta" INTEGER,
    "ft_percent" TEXT,
    "ORB" INTEGER,
    "DRB" INTEGER,
    "TRB" INTEGER,
    "AST" INTEGER,
    "STL" INTEGER,
    "BLK" INTEGER,
    "TOV" INTEGER,
    "PTS" INTEGER,
    "team" TEXT NOT NULL,
    "season" INTEGER NOT NULL,

    CONSTRAINT "s2023Average_pkey" PRIMARY KEY ("id")
);
