-- AlterTable
ALTER TABLE "s2023" ALTER COLUMN "field_percent" SET DATA TYPE TEXT,
ALTER COLUMN "three_percent" SET DATA TYPE TEXT,
ALTER COLUMN "two_percent" SET DATA TYPE TEXT,
ALTER COLUMN "ft_percent" SET DATA TYPE TEXT;
